version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/mattermost/mattermost-plugin-memes
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  untagged-build:
    jobs:
      - test
